### ISSUE TITLE
Foundry VTT v10

### ISSUE THREAD

**Issue by sierra4hotel** [sw5e-foundry/sw5e#492]
Not supported for V10.

**Comment by TogaParty** [comment]
I am also experiencing this issue.  The 'upgrade' prompt for the database occurs and seems successful,, but after logging in as a GM the game hangs on the SW5e logo screen.  No console output.

**Comment by unrealkakeman89** [comment]
SW5E is not ready for V10. This was announced on the discord server. When it is V10 compatible it will be announced on the discord server.

**Comment by bollwyvl** [comment]
I've been using [2.0.3.2.3.2](https://github.com/unrealkakeman89/sw5e/releases/tag/2.0.3.2.3.2) with v10, and things seem to be working fine in test settings.

Aside: while working on https://github.com/fantasycalendar/FoundryVTT-ItemPiles/pull/225 (any feedback there  e.g. on the correct icon for credits, would be lovely!), i did note a fair amount of console warnings about use of various deprecated APIs, some of which will sunset in v11:

Terminal:
```
FoundryVTT | 2023-01-05 08:35:25 | [warn] The system "sw5e" is using "name" which is deprecated in favor of "id"
Deprecated since Version 10
Backwards-compatible support will be removed in Version 13
FoundryVTT | 2023-01-05 08:35:25 | [warn] The system "sw5e" contains compendium pack data which uses the deprecated "entity" field which must be migrated to "type"
Deprecated since Version 9
Backwards-compatible support will be removed in Version 11
FoundryVTT | 2023-01-05 08:35:25 | [warn] The system "sw5e" is using "author" which is deprecated in favor of "authors"
Deprecated since Version 9
Backwards-compatible support will be removed in Version 11
FoundryVTT | 2023-01-05 08:35:25 | [warn] The system "sw5e" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object
Deprecated since Version 10
Backwards-compatible support will be removed in Version 13

```

**Comment by Ikaguia** [comment]
v10 is now fully supported with https://github.com/sw5e-foundry/sw5e/releases/tag/2.0.3.2.3.7
