### ISSUE TITLE
Split Modifications Compendium

### ISSUE THREAD

**Issue by zeldafreak6245** [sw5e-foundry/sw5e#504]
Please consider organizing modifications via specific compendiums. This would be great for DMs who like making shops and roll tables without having to search through ALL modifications at once. 

I have my compendiums labeled as follows and it works pretty well. Please consider implementing something similar:

Modifications: Armor & Shields
Modifications: Blasters
Modifications: Clothing
Modifications: Cybernetics
Modifications: Droid Customization
Modifications: Force
Modifications: Tech
Modifications: Vibroweapons

![image](https://user-images.githubusercontent.com/117317204/199603248-0294698b-5d07-4343-8545-616b002087c4.png)

**Comment by Ikaguia** [comment]
@zeldafreak6245 would this still be necessary now that the compendium browser is a thing?

**Comment by zeldafreak6245** [comment]
@Ikaguia  As much as it pains me to say it- I think we still should implement it. The browser is REALLY nice, don't get me wrong, but the more refinement the better.

**Comment by Ikaguia** [comment]
@zeldafreak6245 looking at this, I realized that the browser was missing the filter for selecting modification types, should this be a good compromise? Splitting the compendium would require adjusting stuff in a lot of different places in both the importer and the system itself
![image](https://github.com/sw5e-foundry/sw5e/assets/16377028/9b91aebb-9779-42e3-b9d9-d6fb0b9e3f06)

**Comment by zeldafreak6245** [comment]
@Ikaguia  Yes, this should work fine- as long as the players have some way to filter it!
