### ISSUE TITLE
Not allowing me to add powers, background, classes, etc.

### ISSUE THREAD

**Issue by TheBigBadSalad** [sw5e-foundry/sw5e#551]
In foundry, its no longer allowing me to add anything from the compendium to the character by dragging and dropping. It was working fine just a few days ago but now it seems to have stopped.

**Comment by Ikaguia** [comment]
Does this also happen with no other modules enabled?
Can you give us your foundry and sw5e versions?
Also, are there any errors on the console (f12 or cntrl+j)?

**Comment by TheBigBadSalad** [comment]
No modules on, as for the versions I cannot remember since Ive moved to v10
of foundry. The issue was occuring when I would make any configuration
settings changes or change the character sheet. As long as I didnt touch
those it worked fine. However, the issue seems to be resolved after moving
everything to v10 of foundry.
