### ISSUE TITLE
Profile picture + temp/max hp not sitting correctly 

### ISSUE THREAD

**Issue by JavaShipped** [sw5e-foundry/sw5e#636]
Foundry V10 291
SW5e: 2.1.5.2.4.5
Mods: 0

Two issues I noticed
1. Profile pictures for some (not all) monsters from any compendium were being pushed down past the section limit
2. Temp and max HP stacked vertically and pushing past the section limit

![image](https://user-images.githubusercontent.com/29931954/235806036-bd8aef78-3ef2-4716-ace6-418c175bf334.png)

I think I have a fix for this (removing one line of code) that I will create a PR for. https://github.com/sw5e-foundry/sw5e/pull/637

After: 
![image](https://user-images.githubusercontent.com/29931954/235806448-d0dcd840-ac83-48d9-85b8-7a06bb228bc4.png)

**Comment by Ikaguia** [comment]
This has been fixed for some time.
![image](https://github.com/sw5e-foundry/sw5e/assets/16377028/802fb233-a84c-4a05-aa24-a57140d5a28a)
