### ISSUE TITLE
Wrong installation Manifest URL in the README.md

### ISSUE THREAD

**Issue by ThiagoS332** [sw5e-foundry/sw5e#675]
**Current README.md URL:** [link](https://raw.githubusercontent.com/unrealkakeman89/sw5e/master/system.json)

**Expected README.md URL:** [link](https://github.com/sw5e-foundry/sw5e/releases/latest/download/system.json)

**Issue Details:**
Hello,
I noticed that the README.md file in the repository has an incorrect URL for the system.json file. The current URL mentioned in the README.md points to an old version of the file, which is no longer up to date. The correct URL should be the latest release version of the system.json file.

**Steps to Reproduce:**
Navigate to the [README.md](https://github.com/sw5e-foundry/sw5e/blob/main/README.md) file in the repository.
Locate the section mentioning the URL for the system.json file.
Click on the provided URL, which currently leads to an old version of the file.
Expected Behavior:
The README.md file should contain the correct URL that points to the latest release version of the system.json file.

**Actual Behavior:**
The README.md file contains an outdated URL that leads to an old version of the system.json file.

**Additional Information:**
It would be great if the README.md file could be updated with the correct URL, allowing users to easily access the latest version of the system.json file. This will ensure a smooth experience for anyone using the repository.

Thank you for your attention to this matter, and I appreciate your help in resolving this issue.

**Comment by gunqqer** [comment]
Fixed by #678
