### ISSUE TITLE
Tech / Force Resistance

### ISSUE THREAD

**Issue by zeldafreak6245** [sw5e-foundry/sw5e#702]
**Is your feature request related to a problem? Please describe.**
Source: Discord
OP: Blues_Otters
Date: 11/20/2022

It appears that both Tech and Force resistances have ability attributes, but they do not appear to apply the correct resistances / conditions. 

Per Ikaguia, "Do keep in mind that most of these flags currently do not have any effects on your sheet or rolls"

**Describe the solution you'd like**
I would like the features to be applied appropriately, or at least a key created to allow for custom / manual options.

**Comment by Ikaguia** [comment]
This is fixed for the next release.
closedMind, forceContention, nimbleReflexes, adaptiveResilience, techResistance will all now set the default roll mode to advantage for the appropriate powers.
![image](https://github.com/sw5e-foundry/sw5e/assets/16377028/fd891846-660a-427a-b09b-1fb166ba2ae8)
