### ISSUE TITLE
Favorites Tab not Working

### ISSUE THREAD

**Issue by zeldafreak6245** [sw5e-foundry/sw5e#703]
**Describe the bug**
Favoriting an item does nothing. 

**To Reproduce**
1. Go to character sheet
2. Favorite an item

**Expected behavior**
The favorited item should appear in "favorites"

**Foundry Information
Foundry version: v10
SW5e version: 2.0.2.2.2.3
OS: N/A

![image](https://github.com/sw5e-foundry/sw5e/assets/117317204/84749c78-f554-444f-9119-2610d9264442)

**Comment by Ikaguia** [comment]
This has already been fixed, I believe since 2.1.5.2.4.0
