### ISSUE TITLE
Encumbrance Tripling

### ISSUE THREAD

**Issue by zeldafreak6245** [sw5e-foundry/sw5e#704]
**Is your feature request related to a problem? Please describe.**
We currently have the Brawny Feat, but nothing to allow for carry capacity TRIPLING. Example, Brawny + Iridonian Grav Arm

**Describe the solution you'd like**
Ideally have a "feature" or key for the Irodian Grav Arm, similar to the brawny option.

**Comment by Ikaguia** [comment]
Has been fixed for a while actually.
