### ISSUE TITLE
All Starships are displayed as "Medium" regardless of Stats. 

### ISSUE THREAD

**Issue by zeldafreak6245** [sw5e-foundry/sw5e#705]
**Describe the bug**
The CSS for a starship always considers its size as medium, even if properly set up as another size.

**To Reproduce**
1. Create a new starship
2. Drag a different size into the starship from the compendium (not medium)
3. Check CSS

**Expected behavior**
The "size" description to be updated accordingly. 

**Screenshots**
![image](https://github.com/sw5e-foundry/sw5e/assets/117317204/1637ffa1-d027-4feb-b570-753a15918547)

**Foundry Information
Foundry version: v10
SW5e version: 2.1.5.2.4.6
OS: Windows 10

**Comment by Ikaguia** [comment]
Fixed for the next release
