### ISSUE TITLE
Add "Remove Crew" option / button to starships

### ISSUE THREAD

**Issue by zeldafreak6245** [sw5e-foundry/sw5e#712]
zeldafreak6245 | Artwork — Today at 11:01 AM
Hey @Ikaguia would it be possible to add some sort of 'clear crew' option to starships? I've had weird issues deploying actors, especially if an actor that was in the ship before was deleted before it was removed from the ship.
I have a feeling there is some lingering data In there preventing others from being able to be added in. (Drag & drop does nothing) I will likely need to build the ship again (no biggie)

Ikaguia — Today at 11:04 AM
I did add steps that would clear data from the starship if a crew was deleted before being removed from the starship.
I see no issue with adding such a button though
Make a post in ⁠system-suggestions so I remember it :P

zeldafreak6245 | Artwork — Today at 11:07 AM
I will add it to the github!

**Comment by Ikaguia** [comment]
https://github.com/sw5e-foundry/sw5e/commit/8d81bb8e7414e0513f2733606821c48a111be208
