### ISSUE TITLE
Unexpected pop up saying unreliable migration due to "Your SW5e system data is from too old"

### ISSUE THREAD

**Issue by wgoff194** [sw5e-foundry/sw5e#715]
I have been on 11 for about 1 1/2 months and my groups sw5e game has been on hold during that time. Today I backed up my data and applied the SW5e beta for 11 over the v10 version for testing. I am getting the following error:

```
foundry.js:68095 Your SW5e system data is from too old a Foundry version and cannot be reliably migrated to the latest version. The process will be attempted, but errors may occur.
```

The pop ups then say updated to version 0. if I refresh the page this continues to pop up. 

Any suggestions to correct this. should I uninstall SW5e and re add the beta? Honestly only care to keep characters so I don't have to recreate them. is There a way to export them so I can import on a new SW5e World?

**Comment by Ikaguia** [comment]
We're tracking down the issue, it is not an error on your end

**Comment by Ikaguia** [comment]
If you download it again, it should be fixed now

**Comment by wgoff194** [comment]
> If you download it again, it should be fixed now

Do I download the recent beta again or download a zip of the git?
