### ISSUE TITLE
Item proficiency label not showing correctly on character sheet (2.2.2)

### ISSUE THREAD

**Issue by afwolfe** [sw5e-foundry/sw5e#722]
**Describe the bug**
When viewing equippable items in the character sheet on beta 2.2.2.2.5.0, the item proficiency label shows as `[object Object]`. 

**To Reproduce**

1. Create or open a player character sheet (NPC and starship sheets are affected too).
2. Add an equippable item, if necessary.
3. Expand the item description.
4. Observe that where the proficiency label should be shown, a label with `[object Object]` appears instead.

**Expected behavior**
The proficiency label is correctly returned and shown for equippable items on the character sheet.

**Screenshots**
![sw5e-equippable-item-bug](https://github.com/sw5e-foundry/sw5e/assets/3718652/52858687-e236-4e8e-9e0c-816881691e58)

**Foundry Information**
Foundry version: 11.306
SW5e version: 2.2.2.2.5.0
OS: Alpine Linux 3.18 (Docker)

**Additional context**
This appears to be related to the `equippableItemChatProperties()` method in [module/data/item/templates/equippable-item.mjs#L62](https://github.com/sw5e-foundry/sw5e/blob/beta/module/data/item/templates/equippable-item.mjs#L62).

In the dnd5e module, `CONFIG.DND5E.proficiencyLevels` is a map of numbers (proficiency multipliers) to strings (labels), but in sw5e `CONFIG.SW5E.proficiencyLevels` is a map of numbers to objects representing some metadata about each proficiency level, including the `label`.

**Comment by Ikaguia** [comment]
That was indeed the issue, simply missing a `.label` there, will be fixed for the next update.
