### ISSUE TITLE
Editing and Rolling Starship Skills throwing errors (2.2.2)

### ISSUE THREAD

**Issue by afwolfe** [sw5e-foundry/sw5e#728]
**Describe the bug**
Rolling and editing starship skills and proficiencies on beta 2.2.2.2.5.0 beta does not work and throws errors in the browser console.

**To Reproduce**
1. Create or open a starship
2. Attempt to change the proficiency
3. Observe that the proficiency does not cycle through the proficiency levels and throws an error in the browser console: [starship-proficiency-error.txt](https://github.com/sw5e-foundry/sw5e/files/12413195/starship-proficiency-error.txt)
4. Attempt to roll a skill check by clicking the skill name
5. Observe that the roll prompt does not appear and an error appears in the browser console: [starship-sheet-skill-roll.txt](https://github.com/sw5e-foundry/sw5e/files/12413198/starship-sheet-skill-roll.txt)
6. Attempt to configure a skill by clicking on the gear when hovering
7. Observe that the skill configuration does not appear and an error appears in the browser console: [starship-sheet-configure-skill.txt](https://github.com/sw5e-foundry/sw5e/files/12413199/starship-sheet-configure-skill.txt)

**Expected behavior**
A user is able to roll and modify skills and skill proficiencies on starship actor sheets.

**Screenshots**
N/A

**Foundry Information**
Foundry version: 11.306
SW5e version: 2.2.2.2.5.0
OS: Alpine Linux 3.18 (Docker)

**Additional context**
This appears to be related to some changes in the other actor sheets in 2.2.2 that were missed for SW5e's unique starship-sheet, including:
* adding a `proficiency-row` class to the skill `li`s and
* `data-skill` becoming `data-key`.

I was able to solve the error by adapting the equivalent section from the swalt-core template and will share a PR shortly.

**Comment by Ikaguia** [comment]
Closing this as the fix has been merged
