### ISSUE TITLE
Imported Character Traits (armorProf, languages, weaponProf) showing as [object Set]

### ISSUE THREAD

**Issue by afwolfe** [sw5e-foundry/sw5e#733]
**Describe the bug**
When using Import Character on SW5e 2.2.2.2.5.0 on Foundry 11, the character's valid traits will import as `[object Set]`, meanwhile custom traits apply correctly to the text field.

**To Reproduce**
1. Create a character on the SW5e website
2. Click "Export to FoundryVTT" and copy the JSON payload
3. Open a SW5e Foundry world, select "Import Character," paste the payload, and click the second "Import Character"
4. Wait for the import to complete
5. Open the character sheet and observe that the following will contain an `[object Set]` where the proficiencies should be selected. Traits automatically applied from other effects are not affected.
    - Languages
    - Armor Proficiencies
    - Weapon Proficiencies
6. Attempting to edit any of these will clear the `[object Set]` from the sheet and the correct values will need manually selected.

**Expected behavior**
An imported character has traits correctly applied.

**Screenshots**
![sw5e-imported-traits](https://github.com/sw5e-foundry/sw5e/assets/3718652/0cbf374e-72d7-4c03-bcef-222b050994d8)

**Foundry Information**
Foundry version: 11.306
SW5e version: 2.2.2.2.5.0
OS: Alpine Linux 3.18 (Docker)

**Additional context**
When looking at an existing Actor object, the `system.traits.armorProf.value`, `system.traits.languages.value`, and `system.traits. weaponProf.value` all appear to be Sets and the CharacterImporter is attempting to pass them to the `_actor.update()` method as Sets.

As an experiment, I tried storing the `value` of each trait as an Array before passing it off to the `update()` method and was able to get them to apply to the character correctly, however I am not sure if this is the right fix.

**Comment by Ikaguia** [comment]
It would indeed be the right fix, this was something we missed when dnd5e changed to using sets on some properties.
