### ISSUE TITLE
When applying an Ability Score Increase to an ability score that has been raised by an effect, the ASI is applied twice.

### ISSUE THREAD

**Issue by afwolfe** [sw5e-foundry/sw5e#788]
**Describe the bug**
All sw5e 2.3.1-based releases are also affected by https://github.com/foundryvtt/dnd5e/issues/2470.

**To Reproduce**
1. Create a new player character
2. Add a species with an ASI granted by an effect
3. Add a class
4. Advance the class to level 4
5. Complete the Ability Score Increase for the character, increasing the stat that is already being modified by the effect.
6. Observe that the ASI is applied twice

**Expected behavior**
The ASI is only applied once to the character's score.

**Foundry Information**
Foundry version: 11.315
SW5e version: 2.3.1.2.6.4

**Additional context**
This issue is closed and is targeted to be fixed in dnd5e 2.4.0. Due to sw5e's extensive use of effects to automatically apply Ability Score Increases from species and other features, this bug has a larger impact in this system and makes class advancements break most character sheets when advancing past level 3.

If there is another 2.3.1-based patch for sw5e, I would appreciate if the fix could be included there.

As a workaround, players could manually disable all effects applying an ASI before leveling up.

**Comment by Ikaguia** [comment]
I'll have to take a look at this fix, but we have already changed species for the next release to use the ASI advancement instead of effects.

**Comment by Ikaguia** [comment]
Seems like a simple enough fix, I'll see what I can do later on today.
Leaving a link to the commit with the fixes for later reference: https://github.com/arbron/dnd5e/commit/23f5de4bc2b94d82b5996db2cf9506549c7f0c16

**Comment by afwolfe** [comment]
> I'll have to take a look at this fix, but we have already changed species for the next release to use the ASI advancement instead of effects.

Thanks, you're awesome @Ikaguia! Looking forward to those changes in the next release too, then.

**Comment by Ikaguia** [comment]
With the https://github.com/sw5e-foundry/sw5e/releases/tag/2.4.0.2.7.0 release, this has been fixed.
